package com.baby_io.baby_io_app.types;

public enum SleepSessionEventType {
  SESSION_STARTED,
  SESSION_PAUSED,
  SESSION_RESUMED,
  SESSION_ENDED,
  SESSION_TERMINATED,
  SENSOR_ALERT_TRIGGERED,
  SENSOR_DATA_LOGGED,
  MUSIC_STARTED,
  MUSIC_STOPPED,
  PERIODIC_MUSIC_PLAYED,
  USER_ATTENDED,
  WAKE_UP_MUSIC_PLAYED
}