spring.application.name=web-api

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI:https://dev-3xpqpzjayt0s15u2.us.auth0.com/}

auth0.audience=${AUTH0_AUDIENCE:https://UberClocked-api}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL:update}
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${POSTGRES_USER:sa}
spring.datasource.password=${POSTGRES_PASSWORD:}
spring.datasource.driver-class-name=${DATASOURCE_DRIVER:org.postgresql.Driver}
mp.api-token=${MP_TOKEN:dummy-token}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${USER:user}
spring.mail.password=${PASSWORD:pass}
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS:true}
spring.mail.default-encoding=UTF-8

app.admin.emails=${ADMIN_EMAILS:santinocolombo13@gmail.com,santiagogarrote2005@gmail.com}