package tome.seeders.filter

import org.springframework.stereotype.Component

@Component
class SmutFilter : Filter {
    private val bannedWords =
        setOf(
            "nsfw",
            "adult",
            "explicit",
            "erotic",
            "erotica",
            "smut",
            "porn",
            "fetish",
            "lewd",
            "nude",
            "nudity",
            "dirty",
            "taboo",
            "uncensored",
            "provocative",
            "xxx",
            "sexual",
            "sex",
            "orgasm",
            "intimate",
            "intercourse",
            "pleasure",
            "seduce",
            "seduction",
            "temptation",
            "lust",
            "lustful",
            "desire",
            "passion",
            "spicy",
            "sensual",
            "sultry",
            "flirt",
            "affair",
            "cheating",
            "naughty",
            "steamy",
            "bdsm",
            "bondage",
            "dominant",
            "submission",
            "submissive",
            "dominatrix",
            "master",
            "slave",
            "kink",
            "whip",
            "leather",
            "restraint",
            "punishment",
            "incest",
            "stepbrother",
            "stepsister",
            "stepfather",
            "stepmother",
            "taboo romance",
            "forbidden love",
            "taboo relationship",
            "harem",
            "reverse harem",
            "omegaverse",
            "alpha male",
            "dark romance",
            "billionaire romance",
            "mafia romance",
            "teacher student",
            "age gap",
            "daddy",
            "mommy",
            "sugar baby",
            "sugar daddy",
            "camgirl",
            "cam boy",
            "webcam",
            "escort",
            "prostitute",
            "prostitution",
            "sex worker",
            "porn star",
            "adult film",
            "rape",
            "molest",
            "assault",
            "torture",
            "snuff",
            "gore",
            "graphic violence",
            "hot",
            "hotter",
            "gay",
            "#Girlboss",
            "Virgin",
            "virgin",
            "'Til Death",
            "#Girlboss",
        )

    override fun isValid(text: String): Boolean {
        val normalized = text.lowercase().trim()
        return bannedWords.none { banned ->
            normalized.contains(banned.lowercase())
        }
    }
}
